services:
  mysql_db:
    image: mysql:latest
    container_name: mysql_database
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend_network

volumes:
  mysql_data:

networks:
  backend_network:
    driver: bridge